"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var myPoint = new point_1.Point(10, 10);
console.log(myPoint);
myPoint.setX(20);
myPoint.setY(20);
console.log(myPoint.getX());
console.log(myPoint.getY());
var string = myPoint.toString();
console.log(string);
console.log(typeof string);
console.log(myPoint.distanceToOrigin());
var punto2 = new point_1.Point(10, 10);
console.log(myPoint.calculateDistance(punto2));
console.log(myPoint.calculateQuadrant());
myPoint.setX(-10);
console.log(myPoint.calculateQuadrant());
myPoint.setY(-10);
console.log(myPoint.calculateQuadrant());
myPoint.setX(10);
console.log(myPoint.calculateQuadrant());
myPoint.setY(0);
console.log(myPoint.calculateQuadrant());
var punto3 = new point_1.Point(15, 15);
var punto4 = new point_1.Point(16, 17);
var punto5 = new point_1.Point(18, 19);
var points = [punto2, punto3, punto4, punto5];
myPoint.setX(18);
myPoint.setY(18);
console.log(myPoint);
var resultadoMasCercano = myPoint.calculateNearest(points);
console.log(resultadoMasCercano);
console.log(myPoint.calculateNearest(points));
