"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var professional_js_1 = require("./professional.js");
var movie_js_1 = require("./movie.js");
var manquiña = new professional_js_1.Professional('Manuel Manquiña', 71, 84, 1.75, false, 'Española', 0, 'Actor');
var karraElejalde = new professional_js_1.Professional('Karra Elejalde', 60, 85, 1.90, false, 'Española', 0, 'Actor');
var carlosArguiñano = new professional_js_1.Professional('Carlos Arguiñano', 71, 80, 1.35, false, 'Española', 0, 'Actor');
var jordiCruz = new professional_js_1.Professional('Jordi Cruz', 42, 75, 1.75, false, 'Española', 0, 'Actor');
var mariaDeMedeiros = new professional_js_1.Professional('Maria de Medeiros', 59, 60, 1.58, false, 'Portuguesa', 0, 'Actriz');
var albertoSanJuan = new professional_js_1.Professional('Alberto San Juan', 51, 99, 1.63, false, 'Española', 0, 'Actor');
var franciscoRabal = new professional_js_1.Professional('Francisco Rabal', 75, 105, 1.79, true, 'Española', 0, 'Actor');
var fernandoGuillén = new professional_js_1.Professional('Fernando Guillén', 80, 84, 1.45, false, 'Española', 0, 'Actor');
var albertPla = new professional_js_1.Professional('Albert Pla', 135, 77, 1.72, false, 'Española', 0, 'Actor');
var juanmaBajoUlloa = new professional_js_1.Professional('Juanma Bajo Ulloa', 52, 79, 1.67, false, 'Española', 0, 'Director');
var oubiña = new professional_js_1.Professional('Oubiña', 50, 85, 1.75, false, 'Gallega', 1, 'Guionista');
var pabloEscobar = new professional_js_1.Professional('Pablo Escobar', 65, 80, 1.75, false, 'Colombiana', 1, 'Productor');
var reparto = [manquiña, karraElejalde, carlosArguiñano, jordiCruz, mariaDeMedeiros, albertoSanJuan, franciscoRabal, fernandoGuillén, albertPla];
var airbag = new movie_js_1.Movie('Airbag', 1997, 'Española', 'Comedia');
airbag.setActors(reparto);
airbag.setDirector(juanmaBajoUlloa);
airbag.setWriter(oubiña);
airbag.setProducer(pabloEscobar);
airbag.setLanguage('Español');
airbag.setPlataforma('Toilet times');
airbag.setIsMCU(false);
airbag.setMainCharacterName('Carlos Arguiñano');
airbag.setDistributor('La Vaquinha tiesa');
airbag.printMovie();
